### ISSUE TITLE
Tests are randomly failing

### ISSUE THREAD

**Issue by DavidTanner** [fastify/fastify-swagger-ui#110]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

2.0.1

### Node.js version

18, 20, 21

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

*

### Description

When running `npm test` sometimes tests fail with a timeout, but it is not repeatable on demand.  The error has happened on Linux, Windows, and MacOS.

### Steps to Reproduce

`npm run test`

https://github.com/fastify/fastify-swagger-ui/actions/runs/6776721797/job/18418830040
https://github.com/fastify/fastify-swagger-ui/actions/runs/7216288278/job/19662243321

```
# Subtest: test/integration.test.js
    # Subtest: fastify will response swagger csp
        1..1
        ok 1 - should be equivalent
    ok 1 - fastify will response swagger csp # time=591.307ms
    
    1..1
    # time=597.533ms
not ok 4 - test/integration.test.js # time=597.533ms
  ---
  env: {}
  file: test/integration.test.js
  timeout: 30000
  command: /opt/hostedtoolcache/node/18.19.0/x64/bin/node
  args:
    - test/integration.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/fastify-swagger-ui/fastify-swagger-ui
  exitCode: null
  signal: SIGTERM
  ...
```

```
not ok 4 - test/integration.test.js # time=675.262ms
  ---
  env: {}
  file: test/integration.test.js
  timeout: 30000
  command: C:\hostedtoolcache\windows\node\21.1.0\x64\node.exe
  args:
    - test/integration.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: D:\a\fastify-swagger-ui\fastify-swagger-ui
  exitCode: null
  signal: SIGTERM
  ...
```

```
​ FAIL ​ test/route.test.js 89 OK 344.544ms
  command: /Users/user/.nvm/versions/node/v20.8.0/bin/node
  args:
    - test/route.test.js
  exitCode: null
  signal: SIGTERM

​ FAIL ​ TAP
 ✖ test/route.test.js

  test: TAP
  env: {}
  file: test/route.test.js
  timeout: 30000
  command: /Users/user/.nvm/versions/node/v20.8.0/bin/node
  args:
    - test/route.test.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /Users/user/git/open/fastify-swagger-ui
  exitCode: null
  signal: SIGTERM
```
