### ISSUE TITLE
Make the logo and favicon configurable

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-swagger-ui#13]
as titled, we should also brand them as Fastify

**Comment by Xpucmoc-Bockpec** [comment]
I use this trick to change (prepend) all the CSS so you can use a custom logo, hide the top bar, etc.

```css
h2 + a, section .models, .download-url-wrapper {
  display: none!important;
}

.opblock-get {
  background: #ebeef1!important;
}

.opblock-summary-path, .swagger-ui .info .title, h3 {
  color: #002f6c!important;
}

.topbar {
  background-color: #002f6c!important;
}

.opblock-get .opblock-summary-method {
  background-color: #0048a6!important;
}

.topbar-wrapper {
  height: 45px;
  background-repeat: no-repeat;
  background-size: contain;
  background-image: url("hello.svg");
}

.topbar-wrapper img {
  display: none;
}
```

```js
function streamToString (stream) {
  const chunks = [];

  return new Promise((resolve, reject) => {
    stream.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    stream.on('error', (err) => reject(err));
    stream.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
  });
}


fastify.addHook('onSend', async (req, res, payload) => {
  if (req.url === '/docs/static/swagger-ui.css') {
    const styleBuffer = await fs.readFile(path.join(path.resolve('path', 'to', 'styles.css')));

    return styleBuffer.toString() + (await streamToString(payload));
  }
});
```
